# Generated by Django 4.1.7 on 2023-04-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
                ('date_of_joining', models.DateField()),
                ('photo_file_name', models.CharField(max_length=500)),
            ],
        ),
    ]
